cmake_minimum_required(VERSION 3.16)
project(ddr_test CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(ddr_test src/ddr_test.cpp)
target_compile_definitions(ddr_test PRIVATE _FILE_OFFSET_BITS=64)
target_compile_options(ddr_test PRIVATE -Wall -Wextra -Wpedantic)
add_executable(ddr_set_address src/ddr_set_address.cpp)
target_compile_definitions(ddr_set_address PRIVATE _FILE_OFFSET_BITS=64)
target_compile_options(ddr_set_address PRIVATE -Wall -Wextra -Wpedantic)
